- __test__/integration/servicing_api.spec.ts
- __test__/integration/signer_api.spec.ts
- __test__/integration/token_api.spec.ts
- src/apis/token_api.ts
- src/invariants/token.ts
- src/schemas/basic_type_schemas.ts
- src/schemas/custom_formats.ts
- src/schemas/schema_validator.ts
* Adds some tests for Token API, including:
* transferAsync checks that sender has sufficient balance, throw if not the case
* transferFromAsync checks that sender has sufficient balance and allowance
* getBalanceAsync throws if contract does not implement ERC20 interface
* setProxyAllowance throws if contract does not implement the ERC20 interface
* setUnlimitedProxyAllowance throws if contract does not implement the ERC20 interface
* getProxyAllowanceAsync throws if contract does not implement the ERC20 interface
* Removes hack to validate JSONSchema of BigNumbers, by adding custom format validator
> Add tests for token api

- __mocks__/@dharmaprotocol/MockContract.ts
- __mocks__/@dharmaprotocol/contracts.ts
- __test__/integration/order_api/order_api.spec.ts
- __test__/integration/order_api/order_scenario_runner.ts
- __test__/integration/order_api/scenarios/index.ts
- __test__/integration/order_api/scenarios/invalid_orders.ts
- __test__/integration/order_api/scenarios/nonconsensual_orders.ts
- __test__/integration/order_api/scenarios/valid_orders.ts
- __test__/integration/servicing_api.spec.ts
- __test__/integration/signer_api.spec.ts
- __test__/integration/token_api.spec.ts
- __test__/unit/adapters/simple_interest_loan_adapter.spec.ts
- __test__/unit/debt_kernel_wrapper.spec.ts
- __test__/unit/debt_token_wrapper.spec.ts
- __test__/unit/dummy_token_wrapper.spec.ts
- __test__/unit/erc20_wrapper.spec.ts
- __test__/unit/token_registry_wrapper.spec.ts
- __test__/unit/token_transfer_proxy_wrapper.spec.ts
This PR introduces the following changes to  [PR#13](https://github.com/dharmaprotocol/dharma.js/pull/13):
- Fixes unit tests that fail in PR13 due to outdated mocking procedures
- Fixes unit tests that fail in PR13 due to the newly introduced order fill hook introduced by [charta/PR32](https://github.com/dharmaprotocol/charta/pull/32)  (which requires that a terms contract specified in a debt order return `true` to `registerTermStart`)
> Patch dharma.js tests that mock pulling contract artifacts

- __test__/unit/blockchain_api/blockchain_api.spec.ts
- __test__/unit/blockchain_api/error_scenario_runner.ts
- __test__/unit/blockchain_api/scenarios/error_scenarios.ts
- __test__/unit/blockchain_api/scenarios/index.ts
- __test__/unit/blockchain_api/scenarios/valid_orders.ts
- src/apis/blockchain_api.ts
- src/types/debt_kernel_error.ts
This PR addresses the fact that our parsing of logs needs to handle scenarios where no errors are to be expected.
Our parsing code is now capable of handling such scenarios, with test cases to prove it. We can add more test cases as we encounter more scenarios.
> Fix for error logs

- __test__/unit/blockchain_api/error_scenario_runner.ts
- __test__/unit/blockchain_api/scenarios/error_scenarios.ts
- __test__/unit/blockchain_api/scenarios/invalid_repayments.ts
Changes:
- remove unused elements from object destructuring
- decompose setup for testing repayment router error scenarios
- document logic for how various scenarios are configured
- `ROUTER_UNAUTHORIZED_TO_REPORT_REPAYMENT ` -> `REPAYMENT_REJECTED_BY_TERMS_CONTRACT`
> Changes to the test suite for the retrieval of repayment router errors

- src/adapters/simple_interest_loan_adapter.ts
- src/apis/blockchain_api.ts
- src/apis/signer_api.ts
- src/apis/token_api.ts
- yarn.lock
This introduces the following changes:
- In several locations, the constructor for `Assertions` was missing its second argument.  This patches those instantiations.
> fix: constructor signature for Assertions needs to be brought up to date

- __test__/integration/servicing_api/runners/get_repayment_schedule.ts
- __test__/integration/servicing_api/scenarios/get_repayment_schedule.ts
- __test__/integration/servicing_api/scenarios/index.ts
- __test__/integration/servicing_api/servicing_api.spec.ts
- __test__/integration/servicing_api/servicing_scenario_runner.ts
- __test__/unit/adapters/simple_interest_loan_adapter.spec.ts
- __test__/unit/types/repayment_schedule.spec.ts
- src/adapters/simple_interest_loan_adapter.ts
- src/apis/contracts_api.ts
- src/apis/servicing_api.ts
- src/types/index.ts
- src/types/repayment_schedule.ts
- Adds `getRepaymentScheduleAsync`, which takes in an issuanceHash and returns a list of repayment dates, to servicing API. This method uses a new type, RepaymentSchedule, which is constructed from amortization unit, timestamp and term length. Its toArray() will return a list of timestamps, which is what is returned by the `getRepaymentScheduleAsync`.
Example usage:
```javascript
const list = await servicingApi.getRepaymentScheduleAsync(issuanceHash);
=> [1521592647, 1521597647] // unix timestamps for repayment schedule
```
TODO: This assumes that the adapter is always the SimpleInterestLoanAdapter. This is wrong to do. However, it's unclear what the best way is to figure out which adapter to use (and we only have the SILAdapter.)
I also think that some of the test setup in the runners …
> feat: add getRepaymentScheduleAsync method on servicing API

- __test__/integration/order_api/order_scenario_runner.ts
- __test__/integration/order_api/scenarios/index.ts
- __test__/integration/order_api/scenarios/invalid_orders.ts
- __test__/integration/servicing_api/runners/get_expected_value_repaid.ts
- __test__/integration/servicing_api/runners/get_value_repaid.ts
- __test__/integration/servicing_api/runners/make_repayment.ts
- __test__/unit/blockchain_api/error_scenario_runner.ts
- __test__/unit/blockchain_api/scenarios/error_scenarios.ts
- __test__/unit/blockchain_api/scenarios/invalid_orders.ts
- __test__/unit/debt_order_wrapper.spec.ts
- src/adapters/base_adapter.ts
- src/adapters/simple_interest_loan_adapter.ts
- src/apis/order_api.ts
- src/apis/signer_api.ts
- src/invariants/order.ts
- src/types/debt_order.ts
- src/wrappers/debt_order_wrapper.ts
This introduces the following changes:
- It was a bit messy for us to have to go through `DebtOrderWrapper` any time we wanted to apply network defaults (i.e. DebtKernel address, etc.) to the debt order, especially if we wanted a DebtOrder type in return, as opposed to a `DebtOrderWrapper`.   This PR decouples applyNetworkDefaults into a namespace of DebtOrder specific functions.
- Fixes tests and functionality that depended on `applyNetworkDefaults`
> fix: decouple applyNetworkDefaults from debt order wrapper

- __test__/integration/servicing_api/runners/get_repayment_schedule.ts
- __test__/unit/adapters/simple_interest_loan_adapter.spec.ts
- src/adapters/simple_interest_loan_adapter.ts
- The `toDebtOrder` method in `SimpleInterestLoanAdapter` was previously only returning a subset of the full debt order fields.  We use the `applyNetworkDefaults` method to attach default values for the debt kernel / repayment router's addresses to the debt order returned by `toDebtOrder`.  This should hopefully resolve issues we are seeing in Bazaar related to mismatching signatures.
- Add tests for the above
- Path a failing tests in get_repayment_schedule
> SimpleInterestLoanAdapter should apply network defaults to debt orders it generates

- __test__/integration/order_api/order_api.spec.ts
- __test__/integration/order_api/scenarios/index.ts
- __test__/integration/servicing_api/runners/get_debts.ts
- __test__/integration/servicing_api/runners/get_expected_value_repaid.ts
- __test__/integration/servicing_api/runners/get_investments.ts
- __test__/integration/servicing_api/runners/get_repayment_schedule.ts
- __test__/integration/servicing_api/runners/get_value_repaid.ts
- __test__/integration/servicing_api/runners/make_repayment.ts
- __test__/integration/servicing_api/servicing_api.spec.ts
- __test__/unit/adapters/simple_interest_loan_adapter.spec.ts
- __test__/unit/blockchain_api/error_scenario_runner.ts
- __test__/unit/blockchain_api/scenarios/index.ts
- Fixes various test suites throughout the codebase that are affected by the changes introduced in #36 
- Importantly, patches all servicing api test runners such that, now, the blockchain is always snapshotted before each test scenario is run.  This helps us prevent mysterious `Debt order has already been filled` errors.
> Patch test suite broken by #36

- __test__/integration/order_api/order_api.spec.ts
- __test__/integration/order_api/scenarios/index.ts
- __test__/integration/servicing_api/runners/get_debts.ts
- __test__/integration/servicing_api/runners/get_expected_value_repaid.ts
- __test__/integration/servicing_api/runners/get_investments.ts
- __test__/integration/servicing_api/runners/get_repayment_schedule.ts
- __test__/integration/servicing_api/runners/get_value_repaid.ts
- __test__/integration/servicing_api/runners/make_repayment.ts
- __test__/integration/servicing_api/servicing_api.spec.ts
- __test__/unit/adapters/simple_interest_loan_adapter.spec.ts
- __test__/unit/blockchain_api/error_scenario_runner.ts
- __test__/unit/blockchain_api/scenarios/index.ts
- package.json
- src/adapters/simple_interest_loan_adapter.ts
- src/apis/contracts_api.ts
- src/apis/servicing_api.ts
- src/schemas/simple_interest_parameters_schema.ts
- src/types/dharma_config.ts
- src/wrappers/contract_wrappers/simple_interest_terms_contract_wrapper.ts
- src/wrappers/contract_wrappers/token_registry_wrapper.ts
- utils/constants.ts
- yarn.lock
- Upgrades the `@dharmaprotocol/contracts` version to 0.0.20
- Updates the SimpleInterestLoanAdapter such that it packs / unpacks parameters according to the new terms contract parameter schema introduced to `charta` in version 0.0.17.
- Updates the way by which `getRepaymentSchedule` resolves which type of terms contract corresponds to a given terms contract address (must be changed now that we no longer have separate terms contracts for each principal token)
NOTE: Tests failing on this PR because patched tests are introduced in a separate PR for readability
> Integrate `@dharmaprotocol/contracts` versions >= 0.0.17 into codebase

- __test__/integration/signer_api.spec.ts
- src/apis/signer_api.ts
- src/invariants/order.ts
- utils/signature_utils.ts
- Add a `shouldAddPersonalMessagePrefix` argument to all relevant signer API methods, to give users the flexibility to interact with different types of signer clients (i.e. Metamask vs. Geth)
- Patch tests associated with this.
The rationale for this has to do with the idiosyncrasies around how Metamask, Geth, Parity, and TestRPC all handle `eth_sign` messages. The crucially important factor seems to be that Geth / Parity / TestRPC all modify signing payloads on users behalf to include data that helps prevent chosen ciphertext attacks (see [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign)), whereas Metamask does *not* do this.
It seems like many of these idiosyncracies will no longer be relevant once ERC721 is finalized.  Until then, …
> Add `shouldAddPersonalMessagePrefix` arg to signer API methods

- src/adapters/simple_interest_loan_adapter.ts
- src/apis/contracts_api.ts
- add explicit type definition for loan order being returned 
- `termsContract` => `termsContractAddress`
- add check for whether returned `symbol` is null or undefined
> Review for #40

- __test__/unit/adapters/simple_interest_loan_adapter.spec.ts
- src/adapters/simple_interest_loan_adapter.ts
- src/apis/contracts_api.ts
- Adds a `fromDebtRegistryEntry` endpoint to the SimpleInterestLoanAdapter.
- Adds tests for the new endpoint.
> feat: add fromDebtRegistryEntry endpoint to adapter

- package.json
- yarn.lock
- Import abi-decoder from our forked version of the repository (linked [here](https://github.com/dharmaprotocol/abi-decoder))
Motivation:
Consensys' abi-decoder has a distribution version that is compiled down to ES5 in their repo, but their package.json file does not point to it as the main entry point.  This creates issues for any projects that may be trying to minify abi-decoder (and in turn, our library, given that we inherit from abi-decoder), given that many minifiers throw on non-ES5 javascript.   Our forked version resolves this issue.
> build: import from forked abi-decoder

- src/apis/contracts_api.ts
- src/wrappers/contract_wrappers/collateralized_simple_interest_terms_contract_wrapper.ts
- re-introduces relative paths for imports from "utils".  For reasons that are currently unknown, our build command is breaking on these relative paths.  In the interest of time and several things blocked on this, I vote we stick with relative paths in the short term.
> fix: relative paths imports for utils

- package.json
- src/adapters/base_adapter.ts
- src/adapters/collateralized_simple_interest_loan_adapter.ts
- src/adapters/simple_interest_loan_adapter.ts
- src/adapters/terms_contract_parameters.ts
- src/apis/contracts_api.ts
- src/invariants/schema.ts
- src/schemas/collateralized_simple_interest_loan_order_schema.ts
- src/schemas/schemas.ts
This PR introduces the `CollateralizedSimpleInterestLoanAdapter` class, which houses three public methods:
```
public async toDebtOrder(
collateralizedSimpleInterestLoanOrder: CollateralizedSimpleInterestLoanOrder,
): Promise<DebtOrder.Instance>;
public async fromDebtOrder(
debtOrder: DebtOrder.Instance,
): Promise<CollateralizedSimpleInterestLoanOrder>;
public async fromDebtRegistryEntry(
entry: DebtRegistryEntry,
): Promise<CollateralizedSimpleInterestLoanOrder>;
```
This PR is blocked by the need for the contracts API to have a method that can return the address of the collateralized simple interest terms contract.
> Introduce `CollateralizedSimpleInterestLoanAdapter`

- .prettierrc.yml
- __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts
- package.json
- src/adapters/base_adapter.ts
- src/adapters/collateralized_simple_interest_loan_adapter.ts
- src/adapters/index.ts
- src/adapters/simple_interest_loan_adapter.ts
- src/adapters/terms_contract_parameters.ts
- src/apis/contracts_api.ts
- src/apis/token_api.ts
- src/invariants/schema.ts
- src/schemas/collateralized_simple_interest_loan_order_schema.ts
- src/schemas/schemas.ts
- src/types/error_parser.ts
This PR introduces the following types:
- `CollateralizedLoanTerms`: responsible for packing and unpacking params
- `CollateralizedAdapterErrors`: represents the errors that can be thrown by the adapter
- `CollateralizedTermsContractParameters`: the interface defining the params
This PR does not include the actual adapter or a test suite. Those will following in future PRs.
This branch merges into the main feature branch: `collateralized-simple-interest-adapter`
> Lay groundwork for CollateralizedSimpleInterest Adapter

- __test__/integration/order_api/order_api.spec.ts
- __test__/integration/order_api/order_scenario_runner.ts
- __test__/integration/order_api/scenarios/index.ts
- __test__/integration/order_api/scenarios/successful_order_generation.ts
- __test__/integration/order_api/scenarios/unsuccessful_order_generation.ts
- src/adapters/adapter.ts
- src/adapters/base_adapter.ts
- src/adapters/collateralized_simple_interest_loan_adapter.ts
- src/adapters/index.ts
- src/adapters/simple_interest_loan_adapter.ts
- src/apis/adapters_api.ts
- src/apis/order_api.ts
- src/invariants/adapter.ts
- src/invariants/index.ts
- Adds a `generate` method to the order API, as described [in Pivotal](https://www.pivotaltracker.com/story/show/156491745)
- Add `getRepaymentSchedule` method to the collateralized simple interest loan adapter
- Add basic test suite for `generate`
> Add `generate` method to the order API

- __test__/integration/servicing_api/runners/make_repayment.ts
- __test__/integration/servicing_api/scenarios/get_expected_value_repaid.ts
- __test__/unit/blockchain_api/error_scenario_runner.ts
- __test__/unit/debt_token_wrapper.spec.ts
- package.json
- src/apis/order_api.ts
- src/apis/servicing_api.ts
- src/invariants/debt_agreement.ts
- src/invariants/order.ts
- src/wrappers/contract_wrappers/debt_token_wrapper.ts
- utils/web3_utils.ts
- yarn.lock
- Bump `@dharmaprotocol/contracts` to 0.0.27
- Fix `DebtTokenContractWrapper` to correspond to new 721 interface
- Fix a whole slew of errors that emerged as a result of the change.
> Bumped charta to 0.0.27

- __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts
- src/adapters/collateralized_simple_interest_loan_adapter.ts
Just renaming a variable here, but it should be pulled into its own file too. Later.
> fix: rename collateralizedAdapter to collateralizerAdapter

- __test__/unit/debt_token_wrapper.spec.ts
- package.json
- src/adapters/collateralized_simple_interest_loan_adapter.ts
- src/adapters/terms_contract_parameters.ts
- src/apis/adapters_api.ts
- src/invariants/index.ts
- src/wrappers/contract_wrappers/debt_token_wrapper.ts
- yarn.lock
- Bump `@dharmaprotocol/contracts` to 0.0.28
- Resolve various build issues throwing typescript errors.
> build: Bump contracts to 0.0.28 and resolve build issues

- src/invariants/debt_token.ts
- Change `tokenBelongsToAccounts` => `belongsToAccount`
- Add `canBeTransferredByAccont` invariant
> feat: add canBeTransferredByAccount invariant

- package.json
- yarn.lock
- Bumps the contracts to version 0.0.29
> build: bump contracts to 0.0.29

- __test__/integration/debt_token_api/debt_token_api.spec.ts
- __test__/integration/debt_token_api/debt_token_scenario_runner.ts
- __test__/integration/debt_token_api/runners/balance_of.ts
- __test__/integration/debt_token_api/runners/index.ts
- __test__/integration/debt_token_api/scenarios/balance_of.ts
- __test__/integration/debt_token_api/scenarios/scenarios.ts
- For readability / preventing file bloat, I've extracted the runners in `DebtTokenScenarioRunner` into separate files that inherit from the same `ScenarioRunner` base class.  I think this will pay dividends in cleanliness as we add test scenarios to the file.
> refactor: extract runners into separate files

- src/invariants/order.ts
- src/schemas/basic_type_schemas.ts
- src/schemas/custom_formats.ts
Note: `.add` is deprecated, as is `isBigNumber` on the instance. Dependency on Truffle.js means we cannot upgrade BigNumber.js at this time.
> fix: bignumber.js formatting issue

- __test__/integration/debt_token_api/debt_token_api.spec.ts
- __test__/integration/debt_token_api/debt_token_scenario_runner.ts
- __test__/integration/debt_token_api/runners/balance_of.ts
- __test__/integration/debt_token_api/runners/index.ts
- __test__/integration/debt_token_api/runners/transfer_from.ts
- __test__/integration/debt_token_api/scenarios/index.ts
- __test__/integration/debt_token_api/scenarios/scenarios.ts
- __test__/integration/debt_token_api/scenarios/successful_transfer_from.ts
- __test__/integration/debt_token_api/scenarios/unsuccessful_transfer_from.ts
- package.json
- src/apis/debt_token_api.ts
- src/invariants/debt_token.ts
- src/invariants/schema.ts
- src/schemas/basic_type_schemas.ts
- src/schemas/schemas.ts
- src/types/transaction_options.ts
- src/wrappers/contract_wrappers/base_contract_wrapper.ts
- src/wrappers/contract_wrappers/debt_token_wrapper.ts
- src/wrappers/contract_wrappers/erc721_receiver_wrapper.ts
- src/wrappers/contract_wrappers/mock_erc721_receiver_wrapper.ts
- src/wrappers/index.ts
- utils/transaction_utils.ts
- yarn.lock
- Introduces wrappers for the `ERC721Receiver` and `MockERC721Receiver` contracts
- The former is used to enforce that addresses are valid recipients of 721 tokens, the latter is used in our test suite to test this functionality
> Add ERC721 Receiver Wrappers

- __test__/integration/debt_token_api/debt_token_api.spec.ts
- __test__/integration/debt_token_api/runners/get_approved.ts
- __test__/integration/debt_token_api/runners/index.ts
- __test__/integration/debt_token_api/scenarios/get_approved.ts
- __test__/integration/debt_token_api/scenarios/index.ts
- __test__/integration/debt_token_api/scenarios/orders.ts
- __test__/integration/debt_token_api/scenarios/scenarios.ts
This PR introduces the `Tokenizable` interface which allows us to inject token IDs into our scenarios to simulate various errors.
> Add error scenarios for `getApproved`

- tslint.json
I'm proposing we remove this rule, since most of our code already doesn't comply with it.
> build: remove object-literal-sort-keys rule in tslint

- package.json
- yarn.lock
- bumps `@dharmaprotocol/contracts` to v0.0.35
> build: bump contracts to v0.0.35

- src/adapters/collateralized_simple_interest_loan_adapter.ts
Note: This actually only checks if the collateral address a NULL address. Not whether there was a CollateralReturned log, or anything like that.
> feat: add public method for checking if collateral has been withdrawn

- __test__/integration/token_api.spec.ts
- __test__/utils/utils.ts
- src/apis/token_api.ts
The basic diff is that we used to have a method to return a list of symbols in dharma.js, but this would return a list of symbols and names.
This could be used to populate the permissions section in plex, and the list of tokens when opening a loan request.
> feat: return more info in tokens list

- __test__/integration/order_api/order_api.spec.ts
- __test__/integration/order_api/order_scenario_runner.ts
- src/apis/order_api.ts
You can't see this so well in GitHub, for some reason, but the function being added is:
```typescript
/**
* Throws with error message if a given order is not able to be filled.
*
* @param {DebtOrder.Instance} debtOrder
* @param {TxData} txOptions
* @returns {Promise<void>}
*/
public async assertFillableAsync(
debtOrder: DebtOrder.Instance,
txOptions?: TxData,
): Promise<void> {
const {
debtKernel,
debtToken,
tokenTransferProxy,
} = await this.contracts.loadDharmaContractsAsync(txOptions);
await this.assertValidityInvariantsAsync(debtOrder, debtKernel, debtToken);
await this.assertConsensualityInvariants(debtOrder, txOptions);
await this.assertCreditorBalanceAndAllowanceInvariantsAsync(
debtOrder,
tokenTransferProxy,
txOptions,
);
await this.assertValidLoanOrder(debtOrder);
}
```
> feat: add function assertFillableAsync

- src/types/token_amount.ts
We use the union type discrimination pattern afforded by typescript to pass in a union type to the constructor and switch on the various ways in which the user can instantiate a `TokenAmount`.
We deprecated the static initializers in favor of this approach.
See documentation for union type discrimination here:
https://basarat.gitbooks.io/typescript/docs/types/discriminated-unions.html
> Remove private keyword in favor of union type discrimination

- package.json
- yarn.lock
- bumps the `@dharmaprotocol/contracts` version to 0.0.40
> build: bump charta to mainnet closed beta

- .hound.yml
- webpack.config.js
- A bug had been reported in which importing `dharma.js` in non-ES6 syntax (i.e. `const Dharma = require("@dharmaprotocol/dharma.js")`) lead to users having to use really wonky instantiation syntax (i.e `const dharma = new Dharma(...)` wouldn't work but `const dharma = new Dharma.default(...)` would). This fixes our webpack configuration to address this issue.  See [here](https://github.com/webpack/webpack/issues/3929) for more details
> build: fix umd default export

- __test__/integration/adapters/collateralized_simple_interest_loan_adapter/runners/return_collateral_runner.ts
- __test__/integration/adapters/collateralized_simple_interest_loan_adapter/runners/seize_collateral_runner.ts
- __test__/integration/debt_token_api/runners/approve.ts
- __test__/integration/debt_token_api/runners/get_approved.ts
- __test__/integration/debt_token_api/runners/is_approved_for_all.ts
- __test__/integration/debt_token_api/runners/owner_of.ts
- __test__/integration/debt_token_api/runners/set_approval_for_all.ts
- __test__/integration/debt_token_api/runners/transfer.ts
- __test__/integration/debt_token_api/runners/transfer_base.ts
- __test__/integration/debt_token_api/runners/transfer_from.ts
- src/adapters/collateralized_simple_interest_loan_adapter.ts
- src/apis/debt_token_api.ts
- src/wrappers/contract_wrappers/collateralized_simple_interest_terms_contract_wrapper.ts
- src/wrappers/contract_wrappers/collateralizer_wrapper.ts
- src/wrappers/contract_wrappers/debt_token_wrapper.ts
- src/wrappers/contract_wrappers/dummy_token_wrapper.ts
- src/wrappers/contract_wrappers/erc20_wrapper.ts
- src/wrappers/contract_wrappers/token_transfer_proxy_wrapper.ts
Renames the following functions:
approve => approveAsync
setApprovalForAll => setApprovalForAllAsync
transfer => transferAsync
transferFrom => transferFromAsync
seizeCollateral => seizeCollateralAsync
setApprovalForAll => setApprovalForAllAsync
returnCollateral => returnCollateralAsync
Note: This will break some Dharma.js consumers. Better sooner than later, perhaps.
> refactor: add "async" suffix to transaction methods

- src/adapters/collateralized_simple_interest_loan_adapter.ts
Uses https://lodash.com/docs/4.17.10#assign to extend the default properties with the txData args.
> [157302061] Add tx-data to transaction function params

- package.json
- src/adapters/collateralized_simple_interest_loan_adapter.ts
- utils/constants.ts
- yarn.lock
- Bumps contracts to 0.0.41 to deploy new contracts to Kovan
> build: bumped contracts to 0.0.41

- package.json
- yarn.lock
- Bumps @dharmaprotocol/contracts to 0.1.0
> build: bump dharma contracts onto mainnet

- __test__/integration/order_api/scenarios/invalid_orders.ts
- __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts
- src/adapters/collateralized_simple_interest_loan_adapter.ts
- src/adapters/collateralized_simple_interest_loan_terms.ts
- Throw an error when `collateralAmount = 0` and a user tries filling / generating a loan
- Throw an error when `collateralTokenIndex` refers to an index not currently tracked by our token registry.
> Enforce all Collateralizer invariants

- src/apis/contracts_api.ts
Added this line as a TODO, since it throws when in mainnet if the contract is not deployed.
This function is an anti-pattern since it couples all of the contracts together, meaning it needs to be updated each time the contracts get deployed.
> fix: remove erc721collateralizer from list returned by get contracts
