__test__/unit/adapters/simple_interest_loan_adapter.spec.ts, src/adapters/simple_interest_loan_adapter.ts
Adds assertion to simple interest adapter for packed parameters.
=> Add assertion for valid packed parameters

__test__/unit/debt_order_wrapper.spec.ts, __test__/unit/debt_token_wrapper.spec.ts
- Increases test coverage for debt_token_wrapper
=> Add some basic unit tests for debt_token_wrapper

.circleci/config.yml, package.json
=> test: add circleci

README.md
=> Add CircleCi badge to README

package.json, src/wrappers/contract_wrappers/collateralized_simple_interest_terms_contract_wrapper.ts, yarn.lock
- Bumped version of charta for new contracts
- Added wrapper for the CollateralizedSimpleInterestTermsContract
=> feat: add collateralized simple interest wrapper

src/adapters/simple_interest_loan_adapter.ts
=> bug: update error message for INVALID_TERM_LENGTH

src/apis/debt_token_api.ts
Defines the interface that our DebtTokenAPI class will then implement.
This PR merges into the feature branch.
=> Define `DebtTokenAPI` interface

src/wrappers/contract_wrappers/collateralizer_wrapper.ts, src/wrappers/index.ts
=> feat: add wrapper for collateralizer

__test__/integration/order_api/order_api.spec.ts, __test__/integration/order_api/order_scenario_runner.ts, __test__/integration/servicing_api/runners/get_debts.ts, __test__/integration/servicing_api/runners/get_expected_value_repaid.ts, __test__/integration/servicing_api/runners/get_investments.ts, __test__/integration/servicing_api/runners/get_repayment_schedule.ts, __test__/integration/servicing_api/runners/get_value_repaid.ts, __test__/integration/servicing_api/runners/make_repayment.ts, __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts, __test__/unit/adapters/simple_interest_loan_adapter.spec.ts, __test__/unit/blockchain_api/error_scenario_runner.ts, src/adapters/collateralized_simple_interest_loan_adapter.ts, src/adapters/simple_interest_loan_adapter.ts, src/apis/adapters_api.ts, src/apis/blockchain_api.ts, src/apis/debt_token_api.ts, src/apis/order_api.ts, src/apis/servicing_api.ts, src/apis/signer_api.ts, src/apis/token_api.ts, src/index.ts, src/invariants/account.ts, src/invariants/debt_token.ts, src/invariants/index.ts
- Added invariant for asserting debt token exists
- Refactored so `Assertions` constructor doesn't require web3
- Miscellaneous cleanup
=> Add Debt Token exists assertion

package.json, tslint.json
=> build: use palantir ts-lint recommended latest

__test__/integration/servicing_api/scenarios/index.ts, __test__/integration/servicing_api/scenarios/invalid_make_repayment.ts, __test__/unit/debt_kernel_wrapper.spec.ts, src/apis/contracts_api.ts, src/apis/signer_api.ts
Just some minor tweaks and cleans here.
=> Trivial clean dharma js

package.json
=> Bump version to v0.0.44

__test__/integration/debt_token_api/runners/index.ts, __test__/integration/debt_token_api/scenarios/approve.ts, __test__/integration/debt_token_api/scenarios/balance_of.ts, __test__/integration/servicing_api/scenarios/index.ts, __test__/integration/servicing_api/scenarios/invalid_make_repayment.ts, __test__/unit/adapters/simple_interest_loan_adapter.spec.ts, src/adapters/collateralized_simple_interest_loan_adapter.ts, src/adapters/collateralized_simple_interest_loan_terms.ts, src/adapters/simple_interest_loan_adapter.ts, src/adapters/simple_interest_loan_terms.ts
* Extracted `SimpleInterestLoanTerms` into its own file.
=> refactor: minor clean of dharma.js

package.json, scripts/documentation/typedoc_parser.ts
Example usage:
```bash
S3_URL=s3://json-docs/dharma.js/documentation.json yarn docs:upload
```
=> Docs deploy command

package.json
=> Bump to v0.0.57

__test__/integration/token_api.spec.ts, src/apis/token_api.ts, utils/constants.ts
- Disables usage of EOS w/ dharma.js
=> Disable EOS in light of ERC20 Freeze

__test__/integration/order_api/order_api.spec.ts, __test__/integration/order_api/order_scenario_runner.ts, __test__/integration/order_api/scenarios/invalid_order_cancellations.ts, __test__/integration/order_api/scenarios/valid_order_cancellations.ts, src/apis/order_api.ts, src/apis/signer_api.ts, src/invariants/order.ts, src/wrappers/debt_order_wrapper.ts
* Adds `isCancelled` to order API.
=> feat: add method isCancelled to order API

src/apis/blockchain_api.ts, src/debt_order/index.ts, utils/constants.ts, utils/web3_utils.ts
- Adds a function for determining whether the given debt order is expired.
=> feat: add isExpired method

package.json, yarn.lock
=> build: bump charta version to 0.1.8

src/loan/debt.ts, src/loan/investment.ts, src/loan/loan.ts
Minor bug fixes given API churn
=> Fine tune Debt and Investment classes

__test__/integration/loan/loan_request.spec.ts, __test__/integration/loan/runners/sign_as_underwriter.ts, __test__/integration/loan/scenarios/underwritten_loan_request.ts, __test__/unit/types/underwriter_risk_rating.spec.ts, src/loan/debt_order.ts, src/types/index.ts, src/types/underwriter_risk_rating.ts
- Introduces `UnderwriterRiskRating` type (with unit test suite)
- Integrates `UnderwriterRiskRating` into `DebtOrder`
- Test Coverage for underwriting methods on `LoanRequest`
=> Underwriter Spec
